package Sookmyung.Lingo.domains.enums;

public enum DocumentType {
    CORPORATE_REGISTER, REAL_ESTATE_REGISTER_LAND, REAL_ESTATE_REGISTER_BUILDING, REAL_ESTATE_REGISTRY,ENROLLMENT_CERTIFICATE, FAMILY_RELATIONSHIP_CERTIFICATE
}
